# Generated by Django 3.0.6 on 2020-06-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='amont',
            new_name='amount',
        ),
    ]
