# Generated by Django 3.0.6 on 2020-06-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0003_auto_20200529_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
